// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOBTLtZJG5oY0H1rCO0E-oUcKQ9YDONM',
    appId: '1:221993615283:web:3a25e8205c843f4b7c55c6',
    messagingSenderId: '221993615283',
    projectId: 'geraetepruefung-ff-liekwegen',
    authDomain: 'geraetepruefung-ff-liekwegen.firebaseapp.com',
    databaseURL: 'https://geraetepruefung-ff-liekwegen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geraetepruefung-ff-liekwegen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywXTwAdAVsZQdQnXeXKHMC-2sNWr_KFM',
    appId: '1:221993615283:android:0e0db73cd17bb8b47c55c6',
    messagingSenderId: '221993615283',
    projectId: 'geraetepruefung-ff-liekwegen',
    databaseURL: 'https://geraetepruefung-ff-liekwegen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geraetepruefung-ff-liekwegen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnhF_uvFKZNZYpeW3kIxzj-xUEx5JMKM',
    appId: '1:221993615283:ios:ff9d304c62314f8e7c55c6',
    messagingSenderId: '221993615283',
    projectId: 'geraetepruefung-ff-liekwegen',
    databaseURL: 'https://geraetepruefung-ff-liekwegen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geraetepruefung-ff-liekwegen.appspot.com',
    iosClientId: '221993615283-830oe65b1evhgnqnael2l2mo9k86gopa.apps.googleusercontent.com',
    iosBundleId: 'com.example.geraetepruefungFfLiekwegen',
  );
}
